name: Trigger Blog Deployment

on:
  push:
    branches: [ main ]
    paths:
      - '*.mdx'
  workflow_dispatch:

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{}'
        
      - name: Deployment triggered
        run: echo "✅ Blog deployment triggered successfully!" 